apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - targetPort: 80 #The pod port
      port: 80
      nodePort: 30008 # in the range 30000 - 31...
  selector:
    app: nginx
    tier: frontend