apiVersion: v1
kind: Pod
metadata:
  labels:
    run: high-prio-pod
  name: high-prio-pod
spec:
  containers:
  - image: nginx
    name: high-prio-pod
    resources: {}
  priorityClassName: high-priority
