apiVersion: v1
kind: Pod
metadata:
  labels:
    run: low-prio-pod
  name: low-prio-pod
spec:
  containers:
  - image: nginx
    name: low-prio-pod
    resources: {}
  priorityClassName: low-priority
